version: '3.4'

services:
  infobringjsonserver:
    image: infobringjsonserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
